services:
  # 1st service: Django Cinema API
  web:
    build: . #using my code
    container_name: django-cinema-api
    restart: unless-stopped # it wont restart if we turn off manually
    working_dir: /app #Tells Docker which folder is "Home" inside the box (where to run commands)
    volumes:
      - .:/app #Bind Mount: Any change you make in VS Code happens instantly inside the box (Mirroring)
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db #refer to 2nd service
      - DB_PORT=5432
      - DB_NAME=cinema_db
      - DB_USER=alfa
      - DB_PASSWORD=alfaruqi2005.
      - REDIS_HOST=redis
    env_file: #Tells Docker to check my .env (stored Stripe key & Secret key)
      - .env
    depends_on: #This service need to wait for them
      - db
      - redis

  # 2nd service: The Postgres Database
  db:
    image: postgres:15 #using other's pre-made code
    container_name: cinema-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: alfa
      POSTGRES_PASSWORD: alfaruqi2005.
    ports:
      - "5432:5432"
    volumes: # Its like telling the Db container "Take that storage unit we registered and plug it in right here
      - cinema_pgdata:/var/lib/postgresql/data # Named Volume: Keeps the database data safe (even if container deleted)


  # 3rd service: Redis (for Seat Locking logic)
  redis:
    image: redis:5.0-alpine # alpine is like lite version
    container_name: cinema-redis
    restart: unless-stopped
    ports:
      - "6379:6379"


# The stuff inside "services:" is a Reference, and the stuff inside "volumes:" is the Actual Storage Tank(this part)
# It's like telling Docker, "I want a storage unit named cinema_pgdata to exist."
volumes:
  cinema_pgdata:
