# Generated by Django 6.0.2 on 2026-02-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_showtime_end_at_alter_hall_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_broken',
            field=models.BooleanField(default=False),
        ),
    ]
