"""
Django settings for cinema project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


# --------------- Path and .env ---------------
from pathlib import Path
import os
from dotenv import load_dotenv

# Points to project root folder containing manage.py and .env
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env") # so it recognize that the key is stored in .env 



# --------------- Security & Deployment ---------------

# .environ will auto-throw an error if value in .env missing (no need manually check `if not SECRET_KEY:`)
# while .getenv is optional variable
SECRET_KEY = os.environ['SECRET_KEY'] 

# Switch DEBUG based on environment (stays True in laptop(shows the error), but changed to False in Railway(hide error))
# in .env set to "DEBUG=False" to be Production ; "DEBUG=True" to be Local
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# When we deploy to Railway or AWS, Django needs to know which URLs are allowed to talk to it (need to change to real Domain)
ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', '*').split(',') if host.strip()] # cleans up accidental spaces and trailing commas automatically

# Only trust the reverse proxy (Railway/AWS) headers for Https
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



# --------------- Application definition ---------------

# this part is like (config/app -> provider) in laravel
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # we register manually, so django can access (custom apps)
    'screening.apps.ScreeningConfig', 
    'booking.apps.BookingConfig',
    'payment.apps.PaymentConfig',
    'identity.apps.IdentityConfig',
    'dashboard.apps.DashboardConfig',

    # third part apps
    'rest_framework', # DRF
    'rest_framework_simplejwt.token_blacklist', # So that people can actually log out
    'drf_spectacular', # Swagger/Redoc
]

# like "app/Http/Middleware" in laravel
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Activate WhiteNoise (ORDER MATTERS!)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

APPEND_SLASH = False # so i dont need to write slash "/" at the end URL

ROOT_URLCONF = 'cinema.urls'

# like "resources/views" in laravel
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Entry point for web servers (public/index.php in laravel)
WSGI_APPLICATION = 'cinema.wsgi.application'



# --------------- Database ---------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ['DB_PORT'],
    }
}

# Tell Django: "Don't use the default user. Use the one I made in the 'identity' app."
AUTH_USER_MODEL = 'identity.User'



# --------------- Password validation & Internationalization ---------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True



# --------------- Static files (CSS, JavaScript, Images) and Media ---------------

# Static Files (Admin panel CSS/JS)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media Files (Movie posters/User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# --------------- Stripe ---------------
import stripe

# If they are missing, we WANT it to fail so we don't accidentally use a wrong account
STRIPE_SECRET_KEY = os.environ["STRIPE_SECRET_KEY"]
STRIPE_PUBLISHABLE_KEY = os.environ["STRIPE_PUBLISHABLE_KEY"]

stripe.api_key = STRIPE_SECRET_KEY # We tell the Stripe library to use our secret key



# --------------- DRF and JWT Configuration ---------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', #Swagger/Redoc
}

from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60), # How long the "Key" works
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),    # How long before they must log in again
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "USER_ID_FIELD": "id", # this uses id as PK
    "USER_ID_CLAIM": "user_id",
}



# --------------- REDIS ---------------
REDIS_HOST = os.environ['REDIS_HOST'] # the address of the apartment
REDIS_PORT = os.environ['REDIS_PORT'] # the flat number
REDIS_PASSWORD = os.environ['REDIS_PASSWORD'] # the key to enter that door

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/1", # '/1' makes reserve place only for temp seatlock (/2, etc can be created for other actions)
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}



# --------------- Swagger/Redoc docs ---------------
SPECTACULAR_SETTINGS = {
    'TITLE': 'Cinema Management System API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

