"""
Django settings for cinema project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# --- Deployment part ---
load_dotenv() # so it recognize that the key is stored in .env 
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-%)5vn03xok9@k)&_b9b=6%rox5pwje*3-gtz+8#@a_!h71i0&^') #fallback if .env deleted

# Switch DEBUG based on environment (stays True in laptop(shows the error), but changed to False in Railway(hide error))
# like saying "Assume I'm debugging unless I specifically tell you otherwise."
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# When we deploy to Railway or AWS, Django needs to know which URLs are allowed to talk to it (need to change to real Domain)
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# Only trust the reverse proxy (Railway/AWS) headers for Https
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


if not SECRET_KEY and not DEBUG:
    raise Exception(f"SECRET_KEY must be set in production")


# Application definition
# this part is like (config/app -> provider) in laravel
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'screening.apps.ScreeningConfig', # we register manually, so django can access
    'booking.apps.BookingConfig',
    'payment.apps.PaymentConfig',
    'identity.apps.IdentityConfig',
    'rest_framework', # DRF
    'rest_framework_simplejwt.token_blacklist', # So that people can actually log out
    'drf_spectacular', # Swagger/Redoc
]

# like "app/Http/Middleware" in laravel
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Activate WhiteNoise (ORDER MATTERS!)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

APPEND_SLASH = False # so i dont need to write slash "/" at the end URL

ROOT_URLCONF = 'cinema.urls'

# like "resources/views" in laravel
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Entry point for web servers (public/index.php in laravel)
WSGI_APPLICATION = 'cinema.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'cinema_db'),
        'USER': os.getenv('DB_USER', 'alfa'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'alfaruqi2005.'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'), # Switch to 'db' in Docker
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# django built-in auth validator (we can make custom and override this)
# like "app/Http/Middleware"
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static Files (Admin panel CSS/JS)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media Files (Movie posters/User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# Stripe
import stripe

load_dotenv() # this reads the .env file

# If they are missing, we WANT it to fail so we don't accidentally use a wrong account
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
stripe.api_key = STRIPE_SECRET_KEY # We tell the Stripe library to use our secret key

if not STRIPE_SECRET_KEY:
    raise ValueError("STRIPE_SECRET_KEY is missing! Check your .env file.") # This prevents the app from starting if we forgot the key



# Tell Django: "Don't use the default user. Use the one I made in the 'identity' app."
AUTH_USER_MODEL = 'identity.User'



# Django Rest Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', #Swagger/Redoc
}

from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60), # How long the "Key" works
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),    # How long before they must log in again
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "USER_ID_FIELD": "id", # this uses id as PK
    "USER_ID_CLAIM": "user_id",
}



# REDIS
REDIS_HOST = os.getenv('REDIS_HOST', '127.0.0.1')# This is like the address of the house
REDIS_PASSWORD = os.getenv('REDIS_PASSWORD', '') # This is like key to the front door

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:6379/1", # /1 means database #1 in Redis
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}



# Swagger/Redoc docs
SPECTACULAR_SETTINGS = {
    'TITLE': 'Cinema Management System API',
    'DESCRIPTION': 'High-concurrency booking engine with Redis locking and Stripe integration.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

