# Generated by Django 6.0.4 on 2026-04-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('screening', '0003_seat_is_broken'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(related_name='bookings', to='screening.seat'),
        ),
        migrations.DeleteModel(
            name='SeatLock',
        ),
    ]
