name: Cinema test CI

# 1. WHEN to run: Only when someone makes a Pull Request or Push to the main branch 
on:
  workflow_dispatch: # Allows to manually click "Run" in GitHub UI
  pull_request:
    branches: ["main"] # Only when merge to Main 

jobs:
  test:
    # 2. WHERE to run: On a fresh Ubuntu Linux virtual machine
    runs-on: ubuntu-latest 
    
    steps: #this is the "To-Do List" that the robot follows in order
      - name: Checkout code
        uses: actions/checkout@v4 #This tells the robot to use a pre-made tool
      
        # GitHub doesn't have my local .env, so we make a temporary one (so that docker-compose doesn't crash)
      - name: Create fake temp .env
        run: |
          touch .env
          echo "SECRET_KEY=anyrandomstringabcdefghijklmnopqrstuvwxyz" >> .env
          echo "DEBUG=True" >> .env
          echo "ALLOWED_HOSTS=localhost,127.0.0.1,web" >> .env

          echo "DB_NAME=cinema_db" >> .env
          echo "DB_USER=test_user" >> .env
          echo "DB_PASSWORD=test_password_123" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env

          echo "REDIS_HOST=redis" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_PASSWORD=" >> .env

          echo "STRIPE_PUBLISHABLE_KEY=pk_test_dummy" >> .env
          echo "STRIPE_SECRET_KEY=sk_test_dummy" >> .env

      - name: Build and Run Tests
        # 1. Build images and start services in background
        # 2. Verify PostgreSQL is ready using the test_user from .env
        # 3. Run Django unit tests inside the web container (exec -T reuses the running web)
        # 4. Clean up containers and volumes when done
        run: |
          docker compose up -d --build
          docker compose exec -T db pg_isready -U test_user -d cinema_db
          docker compose exec -T web python manage.py test
          docker compose down -v
